application: ocr-backend
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: api.app


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: latest
- name: ssl
  version: latest

